<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 5 Descriptive Statistics | Tools for Working with Data</title>
  <meta name="description" content="This GitBook describes tools 211 students can use to work with data." />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 5 Descriptive Statistics | Tools for Working with Data" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This GitBook describes tools 211 students can use to work with data." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 5 Descriptive Statistics | Tools for Working with Data" />
  
  <meta name="twitter:description" content="This GitBook describes tools 211 students can use to work with data." />
  

<meta name="author" content="Nicole Sorhagen, Ph.D." />


<meta name="date" content="2021-02-08" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="picturing-data.html"/>
<link rel="next" href="measurement.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A GitBook for Teaching</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> About this book</a></li>
<li class="chapter" data-level="2" data-path="set-up-project-on-rstudio-cloud.html"><a href="set-up-project-on-rstudio-cloud.html"><i class="fa fa-check"></i><b>2</b> Set up project on Rstudio Cloud</a></li>
<li class="chapter" data-level="3" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>3</b> Introduction</a><ul>
<li class="chapter" data-level="3.1" data-path="introduction.html"><a href="introduction.html#make-a-project-in-rstudio-cloud"><i class="fa fa-check"></i><b>3.1</b> Make a project in RStudio cloud</a></li>
<li class="chapter" data-level="3.2" data-path="introduction.html"><a href="introduction.html#windows-in-rstudio"><i class="fa fa-check"></i><b>3.2</b> WINDOWS IN RSTUDIO</a><ul>
<li class="chapter" data-level="3.2.1" data-path="introduction.html"><a href="introduction.html#the-source-pane"><i class="fa fa-check"></i><b>3.2.1</b> The Source Pane</a></li>
<li class="chapter" data-level="3.2.2" data-path="introduction.html"><a href="introduction.html#the-console-pane"><i class="fa fa-check"></i><b>3.2.2</b> The Console Pane</a></li>
<li class="chapter" data-level="3.2.3" data-path="introduction.html"><a href="introduction.html#the-environment-and-history-pane"><i class="fa fa-check"></i><b>3.2.3</b> The Environment And History Pane</a></li>
<li class="chapter" data-level="3.2.4" data-path="introduction.html"><a href="introduction.html#the-filesplotspackageshelp-pane"><i class="fa fa-check"></i><b>3.2.4</b> The Files/Plots/Packages/Help Pane</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="introduction.html"><a href="introduction.html#navigating-and-commands"><i class="fa fa-check"></i><b>3.3</b> NAVIGATING AND COMMANDS</a><ul>
<li class="chapter" data-level="3.3.1" data-path="introduction.html"><a href="introduction.html#packages"><i class="fa fa-check"></i><b>3.3.1</b> Packages</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="introduction.html"><a href="introduction.html#data-things"><i class="fa fa-check"></i><b>3.4</b> DATA THINGS</a><ul>
<li class="chapter" data-level="3.4.1" data-path="introduction.html"><a href="introduction.html#manual-entry"><i class="fa fa-check"></i><b>3.4.1</b> Manual Entry</a></li>
<li class="chapter" data-level="3.4.2" data-path="introduction.html"><a href="introduction.html#upload-data-into-rstudio-cloud"><i class="fa fa-check"></i><b>3.4.2</b> Upload data into RStudio Cloud</a></li>
<li class="chapter" data-level="3.4.3" data-path="introduction.html"><a href="introduction.html#importing-data-from-other-sources"><i class="fa fa-check"></i><b>3.4.3</b> Importing Data From Other Sources</a></li>
<li class="chapter" data-level="3.4.4" data-path="introduction.html"><a href="introduction.html#data-set-up"><i class="fa fa-check"></i><b>3.4.4</b> Data Set Up</a></li>
<li class="chapter" data-level="3.4.5" data-path="introduction.html"><a href="introduction.html#data-transformation"><i class="fa fa-check"></i><b>3.4.5</b> Data Transformation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="picturing-data.html"><a href="picturing-data.html"><i class="fa fa-check"></i><b>4</b> Picturing Data</a><ul>
<li class="chapter" data-level="4.1" data-path="picturing-data.html"><a href="picturing-data.html#research-question"><i class="fa fa-check"></i><b>4.1</b> RESEARCH QUESTION</a></li>
<li class="chapter" data-level="4.2" data-path="picturing-data.html"><a href="picturing-data.html#method"><i class="fa fa-check"></i><b>4.2</b> METHOD</a></li>
<li class="chapter" data-level="4.3" data-path="picturing-data.html"><a href="picturing-data.html#data-analysis-overview"><i class="fa fa-check"></i><b>4.3</b> DATA ANALYSIS OVERVIEW</a></li>
<li class="chapter" data-level="4.4" data-path="picturing-data.html"><a href="picturing-data.html#open-data"><i class="fa fa-check"></i><b>4.4</b> OPEN DATA</a></li>
<li class="chapter" data-level="4.5" data-path="picturing-data.html"><a href="picturing-data.html#frequency-distribution"><i class="fa fa-check"></i><b>4.5</b> FREQUENCY DISTRIBUTION</a></li>
<li class="chapter" data-level="4.6" data-path="picturing-data.html"><a href="picturing-data.html#histograms"><i class="fa fa-check"></i><b>4.6</b> HISTOGRAMS</a></li>
<li class="chapter" data-level="4.7" data-path="picturing-data.html"><a href="picturing-data.html#boxplots"><i class="fa fa-check"></i><b>4.7</b> BOXPLOTS</a></li>
<li class="chapter" data-level="4.8" data-path="picturing-data.html"><a href="picturing-data.html#scatterplots"><i class="fa fa-check"></i><b>4.8</b> SCATTERPLOTS</a></li>
<li class="chapter" data-level="4.9" data-path="picturing-data.html"><a href="picturing-data.html#bar-graph"><i class="fa fa-check"></i><b>4.9</b> BAR GRAPH</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html"><i class="fa fa-check"></i><b>5</b> Descriptive Statistics</a><ul>
<li class="chapter" data-level="5.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#research-question-1"><i class="fa fa-check"></i><b>5.1</b> RESEARCH QUESTION</a></li>
<li class="chapter" data-level="5.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#method-1"><i class="fa fa-check"></i><b>5.2</b> METHOD</a></li>
<li class="chapter" data-level="5.3" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#data-analysis-overview-1"><i class="fa fa-check"></i><b>5.3</b> DATA ANALYSIS OVERVIEW</a></li>
<li class="chapter" data-level="5.4" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#open-data-1"><i class="fa fa-check"></i><b>5.4</b> OPEN DATA</a></li>
<li class="chapter" data-level="5.5" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#descriptive-statistics-1"><i class="fa fa-check"></i><b>5.5</b> DESCRIPTIVE STATISTICS</a><ul>
<li class="chapter" data-level="5.5.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#psych-and-tidyverse"><i class="fa fa-check"></i><b>5.5.1</b> Psych and Tidyverse</a></li>
<li class="chapter" data-level="5.5.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#base-r"><i class="fa fa-check"></i><b>5.5.2</b> Base R</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#descriptive-statistics-by-group"><i class="fa fa-check"></i><b>5.6</b> DESCRIPTIVE STATISTICS BY GROUP</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="measurement.html"><a href="measurement.html"><i class="fa fa-check"></i><b>6</b> Measurement</a><ul>
<li class="chapter" data-level="6.1" data-path="measurement.html"><a href="measurement.html#research-question-2"><i class="fa fa-check"></i><b>6.1</b> RESEARCH QUESTION</a></li>
<li class="chapter" data-level="6.2" data-path="measurement.html"><a href="measurement.html#method-2"><i class="fa fa-check"></i><b>6.2</b> METHOD</a></li>
<li class="chapter" data-level="6.3" data-path="measurement.html"><a href="measurement.html#data-analysis-overview-2"><i class="fa fa-check"></i><b>6.3</b> DATA ANALYSIS OVERVIEW</a></li>
<li class="chapter" data-level="6.4" data-path="measurement.html"><a href="measurement.html#open-data-2"><i class="fa fa-check"></i><b>6.4</b> OPEN DATA</a></li>
<li class="chapter" data-level="6.5" data-path="measurement.html"><a href="measurement.html#internal-reliability"><i class="fa fa-check"></i><b>6.5</b> INTERNAL RELIABILITY</a><ul>
<li class="chapter" data-level="6.5.1" data-path="measurement.html"><a href="measurement.html#cronbachs-alpha"><i class="fa fa-check"></i><b>6.5.1</b> Cronbach’s Alpha</a></li>
<li class="chapter" data-level="6.5.2" data-path="measurement.html"><a href="measurement.html#mcdonalds-omega"><i class="fa fa-check"></i><b>6.5.2</b> Mcdonald’s Omega</a></li>
<li class="chapter" data-level="6.5.3" data-path="measurement.html"><a href="measurement.html#test-retest-reliability"><i class="fa fa-check"></i><b>6.5.3</b> TEST-RETEST RELIABILITY</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="measurement.html"><a href="measurement.html#criterion-convergent-and-discriminant-validity"><i class="fa fa-check"></i><b>6.6</b> CRITERION, CONVERGENT, AND DISCRIMINANT VALIDITY</a></li>
<li class="chapter" data-level="6.7" data-path="measurement.html"><a href="measurement.html#apa-style-write-up"><i class="fa fa-check"></i><b>6.7</b> APA-STYLE WRITE-UP</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Tools for Working with Data</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="descriptive-statistics" class="section level1">
<h1><span class="header-section-number">Chapter 5</span> Descriptive Statistics</h1>
<p>After you look at your data, the next step in the data analysis process is to compute descriptive statistics. In this chapter you will learn how to use RStudio to compute measures of central tendency and variability.</p>
<div id="research-question-1" class="section level2">
<h2><span class="header-section-number">5.1</span> RESEARCH QUESTION</h2>
<p>Let’s continue with the match.com example from chapters 1 and 2. In this example we are pretending to be interested in the judgement of people on dating apps – its frequency and its relation to age and education.</p>
<p>In the last chapter we looked at tables and graphs that told us a bit about the people in our sample in regard to their education, age, and how often they self-report judging others. In this chapter we will add numbers to this understanding with descriptive statistics.</p>
</div>
<div id="method-1" class="section level2">
<h2><span class="header-section-number">5.2</span> METHOD</h2>
<p>Pretend that you worked with Dr. Amanda Gesselman and her colleagues at the Kinsey Institute to create self-report survey items about how often participants judge others. These items were added to a longer semi-proprietary survey about the attitudes and behaviors of single people in the US. This survey was sent to certain people with accounts on match.com. The people were selected so that the demographics match the most recent US census, with oversampling for gay, lesbian, and bisexual participants. Thousands of people completed the survey. We will use a random sample of 688 people from the total sample here.</p>
</div>
<div id="data-analysis-overview-1" class="section level2">
<h2><span class="header-section-number">5.3</span> DATA ANALYSIS OVERVIEW</h2>
<p>The data is in file matadatacmplt.csv. This is the same dataset that we used in the introduction chapter - except that the total judgment variable is included matadatacmplt and not in the matchdata.csv file.</p>
<ul>
<li>The first column contains arbitrary ID numbers to identify the participants<br />
</li>
<li>The next column contains the participants’ ages<br />
</li>
<li>The third column contains the participants’ highest level of education<br />
</li>
<li>The following 12 columns contain the data from the judgement questions (0 = no; 1 = yes)<br />
</li>
<li>The judgmt column contains the total number of times the participants reported judging others on the 12 items. (this is the variable you made in the data transformation section of the introduction chapter)<br />
</li>
<li>The remaining variables are not relevant to the current chapter, so they are not defined here.</li>
</ul>
<p>After the data is opened and you have looked at the data with tables and graphs, the next step is to compute descriptive statistics. Descriptive statistics refer to measures of central tendency and variability. Measures of central tendency describe the middle of a distribution of scores. These statistics include the mean, median, and mode. Measures of variability describe the spread or dispersion of the distribution. The standard deviation, variance, and range are common measures of variability. Descriptive statistics are often calculated for the whole sample and also separately for different levels of a categorical variable.</p>
</div>
<div id="open-data-1" class="section level2">
<h2><span class="header-section-number">5.4</span> OPEN DATA</h2>
<p>First assign the dataset to an object called match (or whatever you prefer). You can do this with the point and click method by selecting from the environment menu:</p>
<p>IMPORT DATASET -&gt; FROM TEXT (READR)</p>
<p><img src="img/3R.1.png" /></p>
<p>Click the BROWSE button and then navigate to your file’s location on your computer. Then click OPEN and then IMPORT.</p>
<p>Or you could use the following code:</p>
<p><code>library(readr)</code><br />
<code>match &lt;- read_csv("matchdatacmplt.csv")</code></p>
<ul>
<li>This command is telling R to assign the data in the matchdatacomplt.csv file to an object called match.</li>
</ul>
<p>Your screen should look like this after the data is imported:</p>
<p><img src="img/3R.2.png" /></p>
</div>
<div id="descriptive-statistics-1" class="section level2">
<h2><span class="header-section-number">5.5</span> DESCRIPTIVE STATISTICS</h2>
<p>This section reviews two ways to compute descriptive statistics in RStudio. First, we will compute descriptive statistics using the psych and tidyverse packages. Then we will review how to use base R to compute them.</p>
<div id="psych-and-tidyverse" class="section level3">
<h3><span class="header-section-number">5.5.1</span> Psych and Tidyverse</h3>
<p>Let’s first load tidyverse, so that we can use pipes (<code>%&gt;%</code>) in our commands:</p>
<p><code>library(tidyverse)</code><br />
(or you could use the point and click method described in chapter 1)</p>
<p>Then load the psych package:</p>
<p><code>library(psych)</code><br />
(or you could use the point and click method described in chapter 1)</p>
<p>Let’s compute descriptive statistics for the judgmental and age variables with the describe function of the psych package. This function was made to compute common descriptive statistics in psychology research. Here is the command:</p>
<p><code>DataObject %&gt;%</code><br />
<code>describe()</code></p>
<ul>
<li>Replace DataObject with the name of the object that is storing the data</li>
</ul>
<p>In the current example the command looks like this:</p>
<p><code>match %&gt;%</code><br />
<code>describe()</code></p>
<ul>
<li>This command is saying to first go to the dataset named match and then describe it<br />
After this command is run, your screen should look like this:</li>
</ul>
<p><img src="img/3R.3.png" /></p>
<p>The first column lists the variable names. The vars columns numbers the variables. The next column reports the number of valid data points for each variable. The next is the mean. The sd in the following column stands for standard deviation. After the standard deviation is the median. In the next few columns trim stands for the trimmed mean; mad stands for median absolute deviation; min stands for minimum; max stands for maximum. The se in the last column stands for standard error.</p>
<p>You can see that every variable in the match data set is listed in the first column. However, the statistics for some of the variables are meaningless, like the statistics listed in the id row for example (the mean of an arbitrary ID number doesn’t mean anything). Also, descriptive statistics cannot be calculated for categorical variables (which can result in warnings).</p>
<p>The select command can be added in order to calculate descriptive statistics for only certain variables (use the pull function to select one variable). For example, this is the command to select only the age and judgment variables:</p>
<p><code>match %&gt;%</code><br />
<code>select(age, judgmt) %&gt;%</code><br />
<code>describe()</code></p>
<ul>
<li>This command is telling R to use the data in the match dataset then select the age and judgment variables then describe those variables.</li>
</ul>
<p>After you run that command, the follow will appear in the console:</p>
<p><img src="img/3R.4.png" /></p>
<p>The mean age is 36.18 and the median is 33.5. The mean being greater than the median suggests a positive skew to the data because the older aged people in the tail of the distribution pull the mean age (36.18) to be greater than the 50% mark (33.5). The most frequent age is 24. The standard deviation is 12.45 years, which tells us most people are between 23 to 45 (36 +/- 12). The ages range from 18 to 60 years old.</p>
<p>The mean judgmental score is 3.54, the median is 3, and the mode is 0 – suggesting that most people in the sample do not judge people very often (or they don’t admit to it at least). The standard deviation is 3.11, so most people in our sample said they judge other people based on between 0 to 6 things. The range was 0 to 12.</p>
</div>
<div id="base-r" class="section level3">
<h3><span class="header-section-number">5.5.2</span> Base R</h3>
<p>You could also use base R to compute descriptive statistics. There are functions to compute individual statistics. For example, the mean function calculates the mean of a variable. It looks like this:</p>
<p><code>mean(DataObject$VariableName)</code></p>
<ul>
<li>Replace DataObject with the name of the object that is storing the data.<br />
</li>
<li>Replace VariableName with the name of the variable.</li>
</ul>
<p>In the current example, this command would calculate the mean age of everyone in the sample:</p>
<p><code>mean(match$age)</code></p>
<p>The following will appear in the console after that is run from your script:</p>
<p><img src="img/3R.5.png" /></p>
<p>Table 3.1 lists R commands for other common statistics. Replace DataObject with the name of the object that is storing the data and replace VariableName with the name of the variable.</p>
<p><img src="img/table3.1.png" /></p>
<p>Add na.rm = TRUE after in the parenthesis if there is missing data in the variable (i.e. <code>mean(DataObject$VariableName, na.rm = TRUE)</code>)</p>
<p>The summary function (<code>summary(DataObject$VariableName)</code>) calculate minimum, 25% point, median, mean, 75% point, and maximum point at the same time. For example, use the following for code to use the summary function of the judgment variable:</p>
<p><code>summary(match$judgmt)</code></p>
<p>After this is run from the script, the following will appear in the console:</p>
<p><img src="img/3R.6.png" /></p>
</div>
</div>
<div id="descriptive-statistics-by-group" class="section level2">
<h2><span class="header-section-number">5.6</span> DESCRIPTIVE STATISTICS BY GROUP</h2>
<p>Next let’s compute the judgment descriptive statistics separately for each level of the education variable. To do this let’s use the describeBy function of the psych package, which reports basic summary statistics by a grouping variable. Here is the command:</p>
<p><code>DataObject %&gt;%</code>
<code>pull(Variable1Name) %&gt;%</code>
<code>describeBy(DataObject$Variable2Name)</code></p>
<ul>
<li>Replace DataObject with the name of the object that is storing the data.</li>
<li>Replace Variable1Name with the name of the variable that you want to describe. Use the select function instead of the pull function with more than one variable.<br />
</li>
<li>Replace Variable2Name with the name of the grouping variable</li>
</ul>
<p>In the current example the command and results looks like:</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="descriptive-statistics.html#cb10-1"></a>match <span class="op">%&gt;%</span></span>
<span id="cb10-2"><a href="descriptive-statistics.html#cb10-2"></a><span class="st">  </span><span class="kw">pull</span>(judgmt) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb10-3"><a href="descriptive-statistics.html#cb10-3"></a><span class="st">  </span><span class="kw">describeBy</span>(match<span class="op">$</span>edu)</span></code></pre></div>
<pre><code>## 
##  Descriptive statistics by group 
## group: bachelors degree
##    vars   n mean   sd median trimmed  mad min max range skew kurtosis  se
## X1    1 245 3.94 3.15      3    3.62 2.97   0  12    12 0.75     0.01 0.2
## ------------------------------------------------------------ 
## group: graduate or professional degree
##    vars   n mean   sd median trimmed  mad min max range skew kurtosis   se
## X1    1 112 4.29 3.29      4    3.94 2.97   0  12    12 0.79    -0.13 0.31
## ------------------------------------------------------------ 
## group: high school degree or less
##    vars  n mean   sd median trimmed  mad min max range skew kurtosis   se
## X1    1 86 2.27 2.55      2    1.86 2.97   0  12    12 1.37     1.85 0.28
## ------------------------------------------------------------ 
## group: two year degree or some college
##    vars   n mean sd median trimmed  mad min max range skew kurtosis   se
## X1    1 244 3.25  3      3    2.83 2.97   0  12    12 1.08      0.7 0.19</code></pre>
<p>In this table we can see that the mean and median judgmental scores increase with educational attainment (high school or less: mean = 2.27, median = 2; two-year degree or some college: mean = 3.25, median = 3; bachelor’s degree: mean = 3.94, median = 3; graduate or professional degree: mean = 4.29, median = 4). The most common judgmental score was zero for the participants with bachelor’s degrees or less. The mode of the participants with graduate or professional degree was 3.</p>
<p>Based on the standard deviations, there were slightly more variability in the scores at the higher level of education (high school or less = 2.55; two-year degree or some college = 3; bachelor’s degree = 3.15; graduate or professional = 3.29). However, the range was the same for all levels of education.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="picturing-data.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="measurement.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/cjvanlissa/gitbook-demo/edit/master/Descriptives.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Tools for working with data 211.pdf"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
